version: "2"
run:
  tests: true
linters:
  default: none
  enable:
    - errcheck
    - gocritic
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - revive
    - staticcheck
    - unconvert
    - unused
  settings:
    revive:
      rules:
        - name: var-naming
          disabled: true
    staticcheck:
      # Disable SA1019 (using deprecated code) as the existing use of CFB is
      # required for backwards compatibility.
      checks: ["all", "-SA1019"]
    lll:
      line-length: 240
  exclusions:
    generated: lax
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax