run:
  deadline: 240s
  tests: true

linters:
  disable-all: true
  enable:
    - govet
    - golint
    - varcheck
    - structcheck
    - errcheck
    - staticcheck
    - ineffassign
    - unconvert
    - misspell
    - lll
    - nakedret
    - gocritic

linters-settings:
  lll:
    line-length: 240 # Exceptional case its usually 120
issues:
  exclude-use-default: false
