language: go
go:
  - 1.11.x
go_import_path: github.com/teamwork/utils
notifications:
  email: false
  webhooks: http://tw-bot.teamworkops.com:8182/travis/buildstatus
cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/bin

install: |
  ./bin/setup-travis

script: |
  set -e
  cd $HOME/gopath/src/github.com/teamwork/utils
  ./bin/coverage -race ./...
  env GO111MODULE=off ./bin/lint ./...

before_cache: |
  rm "$HOME/.cache/go-build/log.txt"
