language: go
go:
  - 1.9.x
before_install:
  - mv $HOME/gopath/src/github.com/Teamwork $HOME/gopath/src/github.com/teamwork
script:
  - cd $HOME/gopath/src/github.com/teamwork/utils
  - ./bin/test
  - ./bin/coverage
  - ./bin/lint
