language: go
go:
  - 1.8.x
  - 1.9.x
go_import_path: github.com/teamwork/utils
notifications:
  email: false
install:
  - ./bin/setup-travis
script:
  - cd $HOME/gopath/src/github.com/teamwork/utils
  - ./bin/test
  - ./bin/coverage
  - ./bin/lint
