language: go
go:
  - 1.13.x
go_import_path: github.com/teamwork/utils
env:
  - GO111MODULE=on
notifications:
  email: false
  webhooks: http://tw-bot.teamworkops.com:8182/travis/buildstatus
script:
  - 'go test -race -coverprofile=coverage.txt -coverpkg=./... ./...'
after_success:
  - 'bash <(curl -s https://codecov.io/bash)'
